### PR TITLE
Fix get value

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by bloveless** [comment]
What does __print do compared to __toString? I've never seen __print before and can't find any docs on it. It seems like most presenters just override the __toString method to do custom printing.

**Comment by Piterden** [comment]
Actually, even I don't know. Just seen it in select FT presenter some time before.

**Comment by Piterden** [comment]
@bloveless https://github.com/anomalylabs/select-field_type/blob/2.2/src/SelectFieldTypePresenter.php line 80

**Comment by RyanThompson** [comment]
It was intended for a human readable __toString alternative - To string is a string alternative of the object usually. __print was a value return method for string

**Comment by Piterden** [comment]
What it should be?
```php
public function __print()
{
    return $this->__toString();
}
```
Like this ^???

**Pull request closed without merging**
